// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
)

type Message struct {
	ID            uuid.UUID `db:"id" json:"id"`
	SalaID        uuid.UUID `db:"sala_id" json:"sala_id"`
	Message       string    `db:"message" json:"message"`
	ReactionCount int64     `db:"reaction_count" json:"reaction_count"`
	Answered      bool      `db:"answered" json:"answered"`
}

type Sala struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Theme string    `db:"theme" json:"theme"`
}
