// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
)

type Message struct {
	ID            uuid.UUID
	SalaID        uuid.UUID
	Message       string
	ReactionCount int64
	Answered      bool
}

type Sala struct {
	ID    uuid.UUID
	Theme string
}
